export const statesCities: Record<string, string[]> = {
  AL: ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"],
  AK: ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Wasilla"],
  AZ: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Tempe", "Gilbert"],
  AR: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"],
  CA: ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Sacramento", "Fresno", "Oakland"],
  CO: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Boulder"],
  CT: ["Bridgeport", "New Haven", "Hartford", "Stamford", "Norwalk"],
  DE: ["Wilmington", "Dover", "Newark", "Middletown"],
  FL: ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale", "St. Petersburg", "Tallahassee"],
  GA: ["Atlanta", "Augusta", "Savannah", "Athens", "Macon"],
  HI: ["Honolulu", "Hilo", "Kailua", "Pearl City"],
  ID: ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello"],
  IL: ["Chicago", "Springfield", "Naperville", "Peoria", "Rockford", "Aurora"],
  IN: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel"],
  IA: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Waterloo"],
  KS: ["Wichita", "Overland Park", "Kansas City", "Topeka", "Olathe"],
  KY: ["Louisville", "Lexington", "Bowling Green", "Covington", "Frankfort"],
  LA: ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles"],
  ME: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"],
  MD: ["Baltimore", "Bethesda", "Rockville", "Gaithersburg", "Annapolis"],
  MA: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"],
  MI: ["Detroit", "Grand Rapids", "Ann Arbor", "Lansing", "Flint"],
  MN: ["Minneapolis", "St. Paul", "Rochester", "Bloomington", "Duluth"],
  MS: ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi"],
  MO: ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence"],
  MT: ["Billings", "Missoula", "Great Falls", "Bozeman", "Helena"],
  NE: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
  NV: ["Las Vegas", "Henderson", "Reno", "Sparks", "Carson City"],
  NH: ["Manchester", "Nashua", "Concord", "Derry", "Salem"],
  NJ: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Trenton", "Camden"],
  NM: ["Albuquerque", "Santa Fe", "Las Cruces", "Rio Rancho", "Roswell"],
  NY: ["New York City", "Buffalo", "Rochester", "Syracuse", "Albany", "Yonkers"],
  NC: ["Charlotte", "Raleigh", "Durham", "Greensboro", "Winston-Salem", "Fayetteville"],
  ND: ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
  OH: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"],
  OK: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond"],
  OR: ["Portland", "Eugene", "Salem", "Bend", "Medford"],
  PA: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Harrisburg"],
  RI: ["Providence", "Warwick", "Cranston", "Pawtucket", "East Providence"],
  SC: ["Charleston", "Columbia", "Greenville", "Myrtle Beach", "Spartanburg"],
  SD: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Mitchell"],
  TN: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Murfreesboro"],
  TX: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington"],
  UT: ["Salt Lake City", "Provo", "West Jordan", "Orem", "Sandy", "St. George"],
  VT: ["Burlington", "Essex", "South Burlington", "Colchester", "Rutland"],
  VA: ["Virginia Beach", "Norfolk", "Richmond", "Chesapeake", "Arlington", "Alexandria"],
  WA: ["Seattle", "Tacoma", "Spokane", "Bellevue", "Vancouver", "Everett"],
  WV: ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling"],
  WI: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"],
  WY: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"],
};

export const stateList = Object.keys(statesCities).sort();
